# Generated by Django 6.0 on 2025-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_idempotentrequest_waitinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='branch',
            field=models.CharField(choices=[('GENEL', 'Genel Diş'), ('COCUK', 'Çocuk Diş')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='work_end',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='work_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
