# Generated by Django 6.0 on 2025-12-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_branch_alter_doctor_branch_alter_doctor_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
